cp210x: Provide baud rate table as bytearray to pyusb
Without this modification the following error is shown:
===
Traceback (most recent call last):
File
".../cp210x-program/./cp210x-program",
line 239, in <module>
    main()
File
".../cp210x-program/./cp210x-program",
line 235, in main
    options.action(options)
File
".../cp210x-program/./cp210x-program",
line 163, in write_cp210x
    eeprom.set_values(values)
File
".../cp210x-program/cp210x/eeprom.py",
line 188, in set_values
    setattr(self, name, value)
File
".../cp210x-program/cp210x/eeprom.py",
line 164, in _set_baudrate_table
    ''.join(cp210x.build_baudrate_cfg(*cfg) for cfg in baudrates))
File
".../cp210x-program/cp210x/eeprom.py",
line 164, in <genexpr>
    ''.join(cp210x.build_baudrate_cfg(*cfg) for cfg in baudrates))
File
".../cp210x-program/cp210x/cp210x.py",
line 111, in build_baudrate_cfg
return (to_binary(baudgen, le=False) + to_binary(timer0reload,
le=False) +
TypeError: can't concat str to bytes
===

Passing strings to pyusb is deprecated. See usb/interop.py: as_array():
> a.fromstring(data) # deprecated since 3.2

Tested with the following setup
- Linux kernel 5.9.0-5-amd64
- Debian bullseye
- python 3.9.1
- python3-usb 1.0.2-2
- $ ./cp210x-program --write-cp210x -F testdata/cp2102-orig.hex

Signed-off-by: Timo Wischer <twischer@freenet.de>